### ISSUE TITLE
DEFAULT_TIMEOUT not defined

### ISSUE THREAD

**Issue by infostud** [nils-ohlmeier/sipsak#90]
Compiling on macOS and FreeBSD
```
src/sipsak.c:158:5: error: use of undeclared identifier 'DEFAULT_TIMEOUT'
                , DEFAULT_TIMEOUT
...
```
Fixed by moving
```
#ifndef DEFAULT_TIMEOUT
#define DEFAULT_TIMEOUT 5000
#endif
```
from src/shoot.c to src/sipsak.h

**Comment by nils-ohlmeier** [comment]
Thanks for the report.

For me it works on MacOS 12.4. sipsak.c should include config.h which should define `DEFAULT_TIMEOUT`.

After running configure the top of my config.h looks like this:
```
/* config.h.  Generated from config.h.in by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Default maximum timeout on waiting for response. */
#define DEFAULT_TIMEOUT 500
```

**Comment by infostud** [comment]
Sorry, I should have followed the installation instructions more carefully.
