### ISSUE TITLE
Any chance to make sipsak compile on Ubuntu 26.04 ?

### ISSUE THREAD

**Issue by rodolfojcj** [nils-ohlmeier/sipsak#103]
Attempting to build sipsak 0.9.8.1 on Ubuntu 26.04 fails, showing an error output like the following one:

    src/auth.c: In function ‘insert_auth’:
    src/auth.c:303:33: error: too many arguments to function ‘MD5Init’; expected 0, have 1
      303 |                                 MD5Init(&Md5Ctx);
          |                                 ^~~~~~~ ~~~~~~~
    In file included from src/auth.c:21:
    src/md5.h:57:6: note: declared here
       57 | void MD5Init PROTO_LIST ((MD5_CTX *));
          |      ^~~~~~~
    src/auth.c:304:33: error: too many arguments to function ‘MD5Update’; expected 0, have 3
      304 |                                 MD5Update(&Md5Ctx, usern, (unsigned int)strlen(usern));
          |                                 ^~~~~~~~~ ~~~~~~~
    src/md5.h:58:6: note: declared here
       58 | void MD5Update PROTO_LIST
          |      ^~~~~~~~~
    src/auth.c:305:33: error: too many arguments to function ‘MD5Update’; expected 0, have 3
      305 |                                 MD5Update(&Md5Ctx, ":", 1);
          |                                 ^~~~~~~~~ ~~~~~~~
    src/md5.h:58:6: note: declared here
       58 | void MD5Update PROTO_LIST
          |      ^~~~~~~~~
    src/auth.c:306:33: error: too many arguments to function ‘MD5Update’; expected 0, have 3
      306 |                                 MD5Update(&Md5Ctx, realm, (unsigned int)strlen(realm));
          |                                 ^~~~~~~~~ ~~~~~~~
    src/md5.h:58:6: note: declared here
       58 | void MD5Update PROTO_LIST
          |      ^~~~~~~~~
    src/auth.c:307:33: error: too many arguments to function ‘MD5Update’; expected 0, have 3
      307 |                                 MD5Update(&Md5Ctx, ":", 1);
          |                                 ^~~~~~~~~ ~~~~~~~
    src/md5.h:58:6: note: declared here
       58 | void MD5Update PROTO_LIST
          |      ^~~~~~~~~
    src/auth.c:308:33: error: too many arguments to function ‘MD5Update’; expected 0, have 3
      308 |                                 MD5Update(&Md5Ctx, password, (unsigned int)strlen(password));
          |                                 ^~~~~~~~~ ~~~~~~~
    src/md5.h:58:6: note: declared here
       58 | void MD5Update PROTO_LIST
          |      ^~~~~~~~~
    src/auth.c:309:33: error: too many arguments to function ‘MD5Final’; expected 0, have 2
      309 |                                 MD5Final(&ha1[0], &Md5Ctx);
          |                                 ^~~~~~~~ ~~~~~~~
    src/md5.h:60:6: note: declared here
       60 | void MD5Final PROTO_LIST ((unsigned char [16], MD5_CTX *));
          |      ^~~~~~~~
    src/auth.c:313:25: error: too many arguments to function ‘MD5Init’; expected 0, have 1
      313 |                         MD5Init(&Md5Ctx);
          |                         ^~~~~~~ ~~~~~~~
    src/md5.h:57:6: note: declared here
       57 | void MD5Init PROTO_LIST ((MD5_CTX *));
          |      ^~~~~~~
    src/auth.c:314:25: error: too many arguments to function ‘MD5Update’; expected 0, have 3
      314 |                         MD5Update(&Md5Ctx, method, (unsigned int)strlen(method));
          |                         ^~~~~~~~~ ~~~~~~~
    src/md5.h:58:6: note: declared here
       58 | void MD5Update PROTO_LIST
          |      ^~~~~~~~~
    src/auth.c:315:25: error: too many arguments to function ‘MD5Update’; expected 0, have 3
      315 |                         MD5Update(&Md5Ctx, ":", 1);
          |                         ^~~~~~~~~ ~~~~~~~
    src/md5.h:58:6: note: declared here
       58 | void MD5Update PROTO_LIST
          |      ^~~~~~~~~
    src/auth.c:316:25: error: too many arguments to function ‘MD5Update’; expected 0, have 3
      316 |                         MD5Update(&Md5Ctx, uri, (unsigned int)strlen(uri));
          |                         ^~~~~~~~~ ~~~~~~~
    src/md5.h:58:6: note: declared here
       58 | void MD5Update PROTO_LIST
          |      ^~~~~~~~~
    src/auth.c:317:25: error: too many arguments to function ‘MD5Final’; expected 0, have 2
      317 |                         MD5Final(&ha2[0], &Md5Ctx);
          |                         ^~~~~~~~ ~~~~~~~
    src/md5.h:60:6: note: declared here
       60 | void MD5Final PROTO_LIST ((unsigned char [16], MD5_CTX *));
          |      ^~~~~~~~
    src/auth.c:320:25: error: too many arguments to function ‘MD5Init’; expected 0, have 1
      320 |                         MD5Init(&Md5Ctx);
          |                         ^~~~~~~ ~~~~~~~
    src/md5.h:57:6: note: declared here
       57 | void MD5Init PROTO_LIST ((MD5_CTX *));
          |      ^~~~~~~
    src/auth.c:321:25: error: too many arguments to function ‘MD5Update’; expected 0, have 3
      321 |                         MD5Update(&Md5Ctx, &ha1_hex, SIPSAK_HASHHEXLEN_MD5);
          |                         ^~~~~~~~~ ~~~~~~~
    src/md5.h:58:6: note: declared here
       58 | void MD5Update PROTO_LIST
          |      ^~~~~~~~~
    src/auth.c:322:25: error: too many arguments to function ‘MD5Update’; expected 0, have 3
      322 |                         MD5Update(&Md5Ctx, ":", 1);
          |                         ^~~~~~~~~ ~~~~~~~
    src/md5.h:58:6: note: declared here
       58 | void MD5Update PROTO_LIST
          |      ^~~~~~~~~
    src/auth.c:323:25: error: too many arguments to function ‘MD5Update’; expected 0, have 3
      323 |                         MD5Update(&Md5Ctx, nonce, (unsigned int)strlen(nonce));
          |                         ^~~~~~~~~ ~~~~~~~
    src/md5.h:58:6: note: declared here
       58 | void MD5Update PROTO_LIST
          |      ^~~~~~~~~
    src/auth.c:324:25: error: too many arguments to function ‘MD5Update’; expected 0, have 3
      324 |                         MD5Update(&Md5Ctx, ":", 1);
          |                         ^~~~~~~~~ ~~~~~~~
    src/md5.h:58:6: note: declared here
       58 | void MD5Update PROTO_LIST
          |      ^~~~~~~~~
    src/auth.c:326:33: error: too many arguments to function ‘MD5Update’; expected 0, have 3
      326 |                                 MD5Update(&Md5Ctx, qop_tmp, (unsigned int)strlen(qop_tmp));
          |                                 ^~~~~~~~~ ~~~~~~~
    src/md5.h:58:6: note: declared here
       58 | void MD5Update PROTO_LIST
          |      ^~~~~~~~~
    src/auth.c:328:25: error: too many arguments to function ‘MD5Update’; expected 0, have 3
      328 |                         MD5Update(&Md5Ctx, &ha2_hex, SIPSAK_HASHHEXLEN_MD5);
          |                         ^~~~~~~~~ ~~~~~~~
    src/md5.h:58:6: note: declared here
       58 | void MD5Update PROTO_LIST
          |      ^~~~~~~~~
    src/auth.c:329:25: error: too many arguments to function ‘MD5Final’; expected 0, have 2
      329 |                         MD5Final(&resp[0], &Md5Ctx);
          |                         ^~~~~~~~ ~~~~~~~~
    src/md5.h:60:6: note: declared here
       60 | void MD5Final PROTO_LIST ((unsigned char [16], MD5_CTX *));
          |      ^~~~~~~~
    make[1]: *** [Makefile:759: src/auth.o] Error 1
    make[1]: Leaving directory '/usr/src/sipsak-0.9.8.1'
    make: *** [Makefile:569: all] Error 2
    make: Leaving directory '/usr/src/sipsak-0.9.8.1'
    'make -C sipsak-0.9.8.1' failed with 512.

Thank you.
